apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-go
  namespace: sopes1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-client-go
  template:
    metadata:
      labels:
        app: grpc-client-go
    spec:
      containers:
        - name: grpc-client-go
          image: roldyoran/go-client:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-client-service #DNS
  namespace: sopes1
spec:
  selector:
    app: grpc-client-go
  ports:
    - protocol: TCP
      port: 8080 # Entrada
      targetPort: 8080 # Salida
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-client-go-hpa
  namespace: sopes1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-client-go
  minReplicas: 2 # Mínimo 2 pods
  maxReplicas: 5 # Máximo número de pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Escalar si el uso promedio de CPU excede el 50%
