# swimming
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-go-swimming
  namespace: sopes1
spec:
  selector:
    matchLabels:
      app: grpc-server-go-swimming
  template:
    metadata:
      labels:
        app: grpc-server-go-swimming
    spec:
      containers:
        - name: grpc-server-go-swimming
          image: roldyoran/go-server-swimming:local7
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.3"
          ports:
            - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service-swimming #DNS
  namespace: sopes1
spec:
  selector:
    app: grpc-server-go-swimming
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP

---
# HorizontalPodAutoscaler para escalar el Deployment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-server-go-swimming-hpa
  namespace: sopes1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-server-go-swimming
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 35



---
# athletics
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-go-athletics
  namespace: sopes1
spec:
  selector:
    matchLabels:
      app: grpc-server-go-athletics
  template:
    metadata:
      labels:
        app: grpc-server-go-athletics
    spec:
      containers:
        - name: grpc-server-go-athletics
          image: roldyoran/go-server-athletics:local7
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.3"
          ports:
            - containerPort: 50052

---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service-athletics #DNS
  namespace: sopes1
spec:
  selector:
    app: grpc-server-go-athletics
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP

---
# HorizontalPodAutoscaler para escalar el Deployment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-server-go-athletics-hpa
  namespace: sopes1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-server-go-athletics
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 35




---
# boxing
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-go-boxing
  namespace: sopes1
spec:
  selector:
    matchLabels:
      app: grpc-server-go-boxing
  template:
    metadata:
      labels:
        app: grpc-server-go-boxing
    spec:
      containers:
        - name: grpc-server-go-boxing
          image: roldyoran/go-server-boxing:local7
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.3"
          ports:
            - containerPort: 50053
            
---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service-boxing #DNS
  namespace: sopes1
spec:
  selector:
    app: grpc-server-go-boxing
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
  type: ClusterIP

---
# HorizontalPodAutoscaler para escalar el Deployment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-server-go-boxing-hpa
  namespace: sopes1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-server-go-boxing
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 35
