# grafana-values.yaml
admin:
  # Establece una contraseña para el administrador
  password: 'admin'  # Cambia esto a una contraseña segura en producción

service:
  type: LoadBalancer  # O usa 'NodePort' si prefieres

ingress:
  enabled: false  # Cambia esto a 'true' si deseas habilitar Ingress

persistence:
  enabled: true
  existingClaim: ""  # Puedes especificar un PVC existente si lo deseas
  accessModes:
    - ReadWriteOnce
  size: 5Gi  # Tamaño del almacenamiento persistente

# Si deseas habilitar la integración con Prometheus
grafana:
  enabled: true
  apiVersion: 1
  datasources:
    - name: Redis
      type: redis
      access: proxy
      url: redis-service:6379  # Reemplaza con el nombre de tu servicio de Redis
      jsonData:
        tlsSkipVerify: false
# Especifica el namespace
namespace: sopes1