apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: student-losers
  namespace: sopes1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: student-winners
  namespace: sopes1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
