apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest 
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m       # Solicitud de CPU
            memory: 128Mi   # Solicitud de memoria
          limits:
            cpu: 200m       # Límite máximo de CPU
            memory: 256Mi   # Límite máximo de memoria
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
